/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
// .gitignore file:
#include "RCC.h"

#include "RCC_reg.h"
#include "BIT_MACROS.h"
#include "GPIO.h"
//#include "NVIC.h"
//#include "exti.h"

//void EXTI0_IRQHandler(void)
//{
//	GPIO_TogglePinValue(GPIOA, PIN1);
//	NVIC_ClearPending(NVIC_EXTI0_IRQ);
//}

//static void _delay_ms(uint32 ms)
//{
//	uint32 i, j;
//	for (i = 0; i < ms; i++)
//	{
//		for (j = 0; j < 1000; j++)
//		{
//			__asm("NOP");
//		}
//	}
//}

int main(void)
{
	//RCC_Config();

	SET_BIT(RCC->RCC_CR, HSION); //Enable HSI.
	while (IS_BIT_CLEAR(RCC->RCC_CR, HSIRDY))
		;							//Polling until HSI is ready.
	SET_BIT(RCC->RCC_CIR, HSIRDYC); //Clear HSI ready flag.

	CLEAR_BIT(RCC->RCC_CFGR, SW0); //Select HSI as system clock.
	CLEAR_BIT(RCC->RCC_CFGR, SW1); //Select HSI as system clock.

	//RCC_EnableCLK(IOPAEN);
	//RCC_EnableCLK(IOPBEN);
	SET_BIT(RCC->RCC_APB2ENR, 3);

	//GPIO_SetPinDirection(GPIOA, PIN1, OUT_PUSH_PULL, OUTPUT_10MHZ);
	//GPIO_SetPinDirection(GPIOB, PIN1, OUT_PUSH_PULL, OUTPUT_10MHZ);

	//GPIO_SetPinValue(GPIOA, PIN1, LOGIC_HIGH);
	//GPIO_SetPinValue(GPIOB, PIN1, LOGIC_HIGH);

	while (1)
	{
		//GPIO_TogglePinValue(GPIOA, PIN1);
		//_delay_ms(1000);
	}
}
