#ifndef DMA_CONFIG_H
#define DMA_CONFIG_H

#include "STD_TYPES.h"

#define DMA_CHANNEL_1			  0

#define DMA_TRANSFER_COMPLETE_INT DISABLE
#define DMA_HALF_TRANSFER_INT	  DISABLE
#define DMA_TRANSFER_ERROR_INT	  DISABLE
#define DMA_MEMORY_INCREMENT	  ENABLE
#define DMA_PERIPHERAL_INCREMENT  ENABLE
#define DMA_CIRCULAR_MODE		  DISABLE
#endif // DMA_CONFIG_H