#ifndef DMA_CONFIG_H
#define DMA_CONFIG_H

#include "STD_TYPES.h"

#define DMA_CHANNEL_1			  0

#define DMA_MEMORY_TO_MEMORY	  TRUE
/* interrupt enable */
#define DMA_TRANSFER_COMPLETE_INT TRUE
#define DMA_HALF_TRANSFER_INT	  FALSE
#define DMA_TRANSFER_ERROR_INT	  FALSE
/* direction */
#define DMA_MEMORY_INCREMENT	  TRUE
#define DMA_PERIPHERAL_INCREMENT  TRUE
#define DMA_CIRCULAR_MODE		  FALSE
#endif // DMA_CONFIG_H