/******************************************************************
 * @Module   	: DIO
 * @Title 	 	: Configuration Header file for DIO Module
 * @Filename 	: DIO_config.h
 * @target  	: ATMEGA32
 * @Author 	 	: Hossam Mohamed
 * @Compiler 	: avr-gcc 
 * @Notes    	: 
 ********************************************************************/

#include "DIO.h"

const DIO_ConfigType DIO_Configuration = {

	.DIO_pins = {
		/* PORTA PINS */
		[PA0_PIN_ID_INDEX] = {.port_num = PORTA_ID,
							  .pin_num = PIN0_ID,
							  .direction = PA0_PIN_DIRECTION,
							  .initial_value = PA0_PIN_INITIAL_VALUE},
		[PA1_PIN_ID_INDEX] = {.port_num = PORTA_ID,
							  .pin_num = PIN1_ID,
							  .direction = PA1_PIN_DIRECTION,
							  .initial_value = PA1_PIN_INITIAL_VALUE},
		[PA2_PIN_ID_INDEX] = {.port_num = PORTA_ID,
							  .pin_num = PIN2_ID,
							  .direction = PA2_PIN_DIRECTION,
							  .initial_value = PA2_PIN_INITIAL_VALUE},
		[PA3_PIN_ID_INDEX] = {.port_num = PORTA_ID,
							  .pin_num = PIN3_ID,
							  .direction = PA3_PIN_DIRECTION,
							  .initial_value = PA3_PIN_INITIAL_VALUE},
		[PA4_PIN_ID_INDEX] = {.port_num = PORTA_ID,
							  .pin_num = PIN4_ID,
							  .direction = PA4_PIN_DIRECTION,
							  .initial_value = PA4_PIN_INITIAL_VALUE},
		[PA5_PIN_ID_INDEX] = {.port_num = PORTA_ID,
							  .pin_num = PIN5_ID,
							  .direction = PA5_PIN_DIRECTION,
							  .initial_value = PA5_PIN_INITIAL_VALUE},
		[PA6_PIN_ID_INDEX] = {.port_num = PORTA_ID,
							  .pin_num = PIN6_ID,
							  .direction = PA6_PIN_DIRECTION,
							  .initial_value = PA6_PIN_INITIAL_VALUE},
		[PA7_PIN_ID_INDEX] = {.port_num = PORTA_ID,
							  .pin_num = PIN7_ID,
							  .direction = PA7_PIN_DIRECTION,
							  .initial_value = PA7_PIN_INITIAL_VALUE},
		/* PORTB PINS */
		[PB0_PIN_ID_INDEX] = {.port_num = PORTB_ID,
							  .pin_num = PIN0_ID,
							  .direction = PB0_PIN_DIRECTION,
							  .initial_value = PB0_PIN_INITIAL_VALUE},
		[PB1_PIN_ID_INDEX] = {.port_num = PORTB_ID,
							  .pin_num = PIN1_ID,
							  .direction = PB1_PIN_DIRECTION,
							  .initial_value = PB1_PIN_INITIAL_VALUE},
		[PB2_PIN_ID_INDEX] = {.port_num = PORTB_ID,
							  .pin_num = PIN2_ID,
							  .direction = PB2_PIN_DIRECTION,
							  .initial_value = PB2_PIN_INITIAL_VALUE},
		[PB3_PIN_ID_INDEX] = {.port_num = PORTB_ID,
							  .pin_num = PIN3_ID,
							  .direction = PB3_PIN_DIRECTION,
							  .initial_value = PB3_PIN_INITIAL_VALUE},
		[PB4_PIN_ID_INDEX] = {.port_num = PORTB_ID,
							  .pin_num = PIN4_ID,
							  .direction = PB4_PIN_DIRECTION,
							  .initial_value = PB4_PIN_INITIAL_VALUE},
		[PB5_PIN_ID_INDEX] = {.port_num = PORTB_ID,
							  .pin_num = PIN5_ID,
							  .direction = PB5_PIN_DIRECTION,
							  .initial_value = PB5_PIN_INITIAL_VALUE},
		[PB6_PIN_ID_INDEX] = {.port_num = PORTB_ID,
							  .pin_num = PIN6_ID,
							  .direction = PB6_PIN_DIRECTION,
							  .initial_value = PB6_PIN_INITIAL_VALUE},
		[PB7_PIN_ID_INDEX] = {.port_num = PORTB_ID,
							  .pin_num = PIN7_ID,
							  .direction = PB7_PIN_DIRECTION,
							  .initial_value = PB7_PIN_INITIAL_VALUE},
		/* PORTC PINS */
		[PC0_PIN_ID_INDEX] = {.port_num = PORTC_ID,
							  .pin_num = PIN0_ID,
							  .direction = PC0_PIN_DIRECTION,
							  .initial_value = PC0_PIN_INITIAL_VALUE},
		[PC1_PIN_ID_INDEX] = {.port_num = PORTC_ID,
							  .pin_num = PIN1_ID,
							  .direction = PC1_PIN_DIRECTION,
							  .initial_value = PC1_PIN_INITIAL_VALUE},
		[PC2_PIN_ID_INDEX] = {.port_num = PORTC_ID,
							  .pin_num = PIN2_ID,
							  .direction = PC2_PIN_DIRECTION,
							  .initial_value = PC2_PIN_INITIAL_VALUE},
		[PC3_PIN_ID_INDEX] = {.port_num = PORTC_ID,
							  .pin_num = PIN3_ID,
							  .direction = PC3_PIN_DIRECTION,
							  .initial_value = PC3_PIN_INITIAL_VALUE},
		[PC4_PIN_ID_INDEX] = {.port_num = PORTC_ID,
							  .pin_num = PIN4_ID,
							  .direction = PC4_PIN_DIRECTION,
							  .initial_value = PC4_PIN_INITIAL_VALUE},
		[PC5_PIN_ID_INDEX] = {.port_num = PORTC_ID,
							  .pin_num = PIN5_ID,
							  .direction = PC5_PIN_DIRECTION,
							  .initial_value = PC5_PIN_INITIAL_VALUE},
		[PC6_PIN_ID_INDEX] = {.port_num = PORTC_ID,
							  .pin_num = PIN6_ID,
							  .direction = PC6_PIN_DIRECTION,
							  .initial_value = PC6_PIN_INITIAL_VALUE},
		[PC7_PIN_ID_INDEX] = {.port_num = PORTC_ID,
							  .pin_num = PIN7_ID,
							  .direction = PC7_PIN_DIRECTION,
							  .initial_value = PC7_PIN_INITIAL_VALUE},
		/* PORTD PINS */
		[PD0_PIN_ID_INDEX] = {.port_num = PORTD_ID,
							  .pin_num = PIN0_ID,
							  .direction = PD0_PIN_DIRECTION,
							  .initial_value = PD0_PIN_INITIAL_VALUE},
		[PD1_PIN_ID_INDEX] = {.port_num = PORTD_ID,
							  .pin_num = PIN1_ID,
							  .direction = PD1_PIN_DIRECTION,
							  .initial_value = PD1_PIN_INITIAL_VALUE},
		[PD2_PIN_ID_INDEX] = {.port_num = PORTD_ID,
							  .pin_num = PIN2_ID,
							  .direction = PD2_PIN_DIRECTION,
							  .initial_value = PD2_PIN_INITIAL_VALUE},
		[PD3_PIN_ID_INDEX] = {.port_num = PORTD_ID,
							  .pin_num = PIN3_ID,
							  .direction = PD3_PIN_DIRECTION,
							  .initial_value = PD3_PIN_INITIAL_VALUE},
		[PD4_PIN_ID_INDEX] = {.port_num = PORTD_ID,
							  .pin_num = PIN4_ID,
							  .direction = PD4_PIN_DIRECTION,
							  .initial_value = PD4_PIN_INITIAL_VALUE},
		[PD5_PIN_ID_INDEX] = {.port_num = PORTD_ID,
							  .pin_num = PIN5_ID,
							  .direction = PD5_PIN_DIRECTION,
							  .initial_value = PD5_PIN_INITIAL_VALUE},
		[PD6_PIN_ID_INDEX] = {.port_num = PORTD_ID,
							  .pin_num = PIN6_ID,
							  .direction = PD6_PIN_DIRECTION,
							  .initial_value = PD6_PIN_INITIAL_VALUE},
		[PD7_PIN_ID_INDEX] = {.port_num = PORTD_ID,
							  .pin_num = PIN7_ID,
							  .direction = PD7_PIN_DIRECTION,
							  .initial_value = PD7_PIN_INITIAL_VALUE},

	}};